In [8]:
import pandas as pd

df = pd.read_csv("data/twitter_training.csv", header=None)
df.head()
df.columns = ['Id', 'Entity', 'Sentiment', 'Content']
df.head()

,Id,Entity,Sentiment,Content
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [9]:
df.columns

Index(['Id', 'Entity', 'Sentiment', 'Content'], dtype='object')

In [10]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

df['clean_text'] = df['Content'].apply(clean_text)

df[['Content', 'clean_text']].head()

,Content,clean_text
0,im getting on borderlands and i will murder yo...,im getting on borderlands and i will murder yo...
1,I am coming to the borders and I will kill you...,i am coming to the borders and i will kill you...
2,im getting on borderlands and i will kill you ...,im getting on borderlands and i will kill you all
3,im coming on borderlands and i will murder you...,im coming on borderlands and i will murder you...
4,im getting on borderlands 2 and i will murder ...,im getting on borderlands and i will murder y...

In [12]:
df.to_csv("data/processed_twitter.csv", index=False)

In [13]:
import os
print(os.listdir("data"))

['processed_twitter.csv', 'twitter_training.csv', 'twitter_validation.csv']